// admin/generate-weights.mjs -- dev-only, run via `npm run generate-weights`, NEVER imported by src/
//
// Trains the 4 canonical signal->intent mappings through brain.js's NeuralNetwork
// (training/weight-export only -- D-04) and writes the extracted weights to
// admin/weights.js as a plain { W1, b1, W2, b2 } object with no brain.js import.
import brain from 'brain.js';
import fs from 'node:fs';

// Class order MUST match inference.js's CLASSES array exactly.
// [confusion, price_doubt, trust_gap, flow_friction]
const canonicalData = [
  { input: [1, 0, 0, 0], output: [1, 0, 0, 0] }, // touch_hesitation -> confusion
  { input: [0, 1, 0, 0], output: [0, 0, 0, 1] }, // blur_incomplete -> flow_friction
  { input: [0, 0, 1, 0], output: [0, 1, 0, 0] }, // scroll_reversal -> price_doubt
  { input: [0, 0, 0, 1], output: [0, 0, 1, 0] }, // back_intent -> trust_gap
];

const net = new brain.NeuralNetwork({
  inputSize: 4,
  hiddenLayers: [4], // INF-01: exactly 4 hidden nodes
  outputSize: 4,
  // 'leaky-relu', NOT 'relu' -- avoids empirically-confirmed dead-neuron training degeneracy
  // (03-RESEARCH.md Common Pitfall #1: plain relu fails 0/15 runs, leaky-relu passes 15/15).
  // inference.js's SHIPPED forward pass still uses genuine ReLU (INF-02); this only affects
  // how brain.js computes gradients during this offline generation step.
  activation: 'leaky-relu',
});

const status = net.train(canonicalData, {
  learningRate: 0.01,
  iterations: 20000, // cap only -- empirically converges well before this via errorThresh
  errorThresh: 0.005,
});

function extractWeights(json) {
  // toJSON()'s layers[0] is the (empty) input layer; layers[1]=hidden, layers[2]=output.
  // Verified against installed brain.js source (03-RESEARCH.md Common Pitfall #3) --
  // do NOT write the raw toJSON() object, its shape does not match forwardPass's expectations.
  return {
    W1: json.layers[1].weights,
    b1: json.layers[1].biases,
    W2: json.layers[2].weights,
    b2: json.layers[2].biases,
  };
}

const weights = extractWeights(net.toJSON());
console.log(`Trained in ${status.iterations} iterations, final error ${status.error}`);

const output = `// GENERATED by admin/generate-weights.mjs -- do not hand-edit.
// Regenerate with: npm run generate-weights
export default ${JSON.stringify(weights, null, 2)};
`;
fs.writeFileSync(new URL('./weights.js', import.meta.url), output);
